### ISSUE TITLE
Use DatePicker component from React95

### ISSUE THREAD

**Issue by arturbien** [c33k/smok95#1]
Just a suggestion- there's DatePicker component in React95 repo that wasn't released yet because we didn't write tests for it yet. It looks like the original Win95 datepicker and you can find it here: https://github.com/arturbien/React95/tree/master/src/DatePicker

<img width="360" alt="Screenshot 2021-03-22 at 09 35 57" src="https://user-images.githubusercontent.com/28541613/111961978-037a5680-8af2-11eb-9659-a73defb284a2.png">

**Comment by c33k** [comment]
Hi Artur.

Perfect! I wanted to use exactly this one, because I saw it on the website and loved it, but didn't see it on the Storebook.

It makes sense. 

Will update to use this one.

Thx a lot!

**Comment by c33k** [comment]
@arturbien the DatePicker component is not exported on the latest dist.

https://github.com/arturbien/React95/blob/master/src/index.js

So I can't use it for now.

**Comment by c33k** [comment]
@arturbien I've created a PR https://github.com/arturbien/React95/pull/230 exporting it.
Not sure if you want to do it now, so block it in case it is not what you want for now.
Meanwhile, I'm testing the component locally in my machine.

Thanks a lot for letting me know.

**Comment by arturbien** [comment]
The component is not exported because it's not ready yet for prod as it is a quite complex one. Mostly due to internationalization (month names / day name abbreviations) issues and other. You can see some discussion about it here: https://github.com/arturbien/React95/issues/194

**Comment by arturbien** [comment]
Damn, this comment supposed to go under the PR 😅 before the component is ready (and nobody is working on it rn) it's better for you to just copy the code and it integrate it in your codebase (you'll probably need to change import paths for components etc).

**Comment by c33k** [comment]
Thx, @arturbien.

Yep, I'm working on it locally and it looks awesome. Thx for letting me know!
